### ISSUE TITLE
rails 4 support

### ISSUE THREAD

**Issue by ghost** [zinenko/vk-ruby#24]
Hi guys,

Can you kindly write, which ruby and rails versions are supported and tested with this gem in README?
Cause I have tried to use it my rails4 app and faced with a problems related to version conflicts.

Also I tried to send vk notifications (as it is described in your blog), 
and it does not works for me.

Thanks kindly,
Bohdan

**Comment by toydestroyer** [comment]
@bmalets,
Adding missing dependency `gem 'yajl-ruby', require: 'yajl'` to my Gemfile works well for me.

**Comment by bmalets** [comment]
Thanks a lot for new updates of your cool gem!
