### ISSUE TITLE
Привет, проект еще жив ?

### ISSUE THREAD

**Issue by Sergogovich** [zinenko/vk-ruby#33]
Если проект жив, напиши, как с тобой связаться, спасибо)

**Comment by zinenko** [comment]
Да

**Comment by Sergogovich** [comment]
как создать приложение, авторизоваться, а то я чет нашел туториал и там постоянно методы не находит, я так понимаю они описаны для ранних версий библиотеки. Буду благодарен, если в свободную минуту уделишь времени и напишешь на почту подробнее о vkapi, а то я не сильно продвинутый и оно для меня что-то сложное)))
